// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/stormstock/fw/event/notifytest2.proto

package stormstock.fw.event;

public final class Notifytest2 {
  private Notifytest2() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface notifytest2OrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 ID = 1;
    boolean hasID();
    int getID();
    
    // required string data = 2;
    boolean hasData();
    String getData();
    
    // required float fdata = 3;
    boolean hasFdata();
    float getFdata();
  }
  public static final class notifytest2 extends
      com.google.protobuf.GeneratedMessage
      implements notifytest2OrBuilder {
    // Use notifytest2.newBuilder() to construct.
    private notifytest2(Builder builder) {
      super(builder);
    }
    private notifytest2(boolean noInit) {}
    
    private static final notifytest2 defaultInstance;
    public static notifytest2 getDefaultInstance() {
      return defaultInstance;
    }
    
    public notifytest2 getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return stormstock.fw.event.Notifytest2.internal_static_stormstock_fw_event_notifytest2_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return stormstock.fw.event.Notifytest2.internal_static_stormstock_fw_event_notifytest2_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 ID = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int iD_;
    public boolean hasID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getID() {
      return iD_;
    }
    
    // required string data = 2;
    public static final int DATA_FIELD_NUMBER = 2;
    private java.lang.Object data_;
    public boolean hasData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          data_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required float fdata = 3;
    public static final int FDATA_FIELD_NUMBER = 3;
    private float fdata_;
    public boolean hasFdata() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public float getFdata() {
      return fdata_;
    }
    
    private void initFields() {
      iD_ = 0;
      data_ = "";
      fdata_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFdata()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, iD_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDataBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, fdata_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, iD_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDataBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, fdata_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static stormstock.fw.event.Notifytest2.notifytest2 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static stormstock.fw.event.Notifytest2.notifytest2 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static stormstock.fw.event.Notifytest2.notifytest2 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static stormstock.fw.event.Notifytest2.notifytest2 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static stormstock.fw.event.Notifytest2.notifytest2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static stormstock.fw.event.Notifytest2.notifytest2 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static stormstock.fw.event.Notifytest2.notifytest2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static stormstock.fw.event.Notifytest2.notifytest2 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static stormstock.fw.event.Notifytest2.notifytest2 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static stormstock.fw.event.Notifytest2.notifytest2 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(stormstock.fw.event.Notifytest2.notifytest2 prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements stormstock.fw.event.Notifytest2.notifytest2OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return stormstock.fw.event.Notifytest2.internal_static_stormstock_fw_event_notifytest2_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return stormstock.fw.event.Notifytest2.internal_static_stormstock_fw_event_notifytest2_fieldAccessorTable;
      }
      
      // Construct using stormstock.fw.event.Notifytest2.notifytest2.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        iD_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        fdata_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return stormstock.fw.event.Notifytest2.notifytest2.getDescriptor();
      }
      
      public stormstock.fw.event.Notifytest2.notifytest2 getDefaultInstanceForType() {
        return stormstock.fw.event.Notifytest2.notifytest2.getDefaultInstance();
      }
      
      public stormstock.fw.event.Notifytest2.notifytest2 build() {
        stormstock.fw.event.Notifytest2.notifytest2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private stormstock.fw.event.Notifytest2.notifytest2 buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        stormstock.fw.event.Notifytest2.notifytest2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public stormstock.fw.event.Notifytest2.notifytest2 buildPartial() {
        stormstock.fw.event.Notifytest2.notifytest2 result = new stormstock.fw.event.Notifytest2.notifytest2(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.iD_ = iD_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.data_ = data_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.fdata_ = fdata_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof stormstock.fw.event.Notifytest2.notifytest2) {
          return mergeFrom((stormstock.fw.event.Notifytest2.notifytest2)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(stormstock.fw.event.Notifytest2.notifytest2 other) {
        if (other == stormstock.fw.event.Notifytest2.notifytest2.getDefaultInstance()) return this;
        if (other.hasID()) {
          setID(other.getID());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        if (other.hasFdata()) {
          setFdata(other.getFdata());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasID()) {
          
          return false;
        }
        if (!hasData()) {
          
          return false;
        }
        if (!hasFdata()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              iD_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              data_ = input.readBytes();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              fdata_ = input.readFloat();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 ID = 1;
      private int iD_ ;
      public boolean hasID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getID() {
        return iD_;
      }
      public Builder setID(int value) {
        bitField0_ |= 0x00000001;
        iD_ = value;
        onChanged();
        return this;
      }
      public Builder clearID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        iD_ = 0;
        onChanged();
        return this;
      }
      
      // required string data = 2;
      private java.lang.Object data_ = "";
      public boolean hasData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setData(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        data_ = value;
        onChanged();
        return this;
      }
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      void setData(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        data_ = value;
        onChanged();
      }
      
      // required float fdata = 3;
      private float fdata_ ;
      public boolean hasFdata() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public float getFdata() {
        return fdata_;
      }
      public Builder setFdata(float value) {
        bitField0_ |= 0x00000004;
        fdata_ = value;
        onChanged();
        return this;
      }
      public Builder clearFdata() {
        bitField0_ = (bitField0_ & ~0x00000004);
        fdata_ = 0F;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:stormstock.fw.event.notifytest2)
    }
    
    static {
      defaultInstance = new notifytest2(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:stormstock.fw.event.notifytest2)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_stormstock_fw_event_notifytest2_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_stormstock_fw_event_notifytest2_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)src/stormstock/fw/event/notifytest2.pr" +
      "oto\022\023stormstock.fw.event\"6\n\013notifytest2\022" +
      "\n\n\002ID\030\001 \002(\005\022\014\n\004data\030\002 \002(\t\022\r\n\005fdata\030\003 \002(\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_stormstock_fw_event_notifytest2_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_stormstock_fw_event_notifytest2_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_stormstock_fw_event_notifytest2_descriptor,
              new java.lang.String[] { "ID", "Data", "Fdata", },
              stormstock.fw.event.Notifytest2.notifytest2.class,
              stormstock.fw.event.Notifytest2.notifytest2.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
