// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/stormstock/fw/event/StockSelectAnalysis.proto

package stormstock.fw.event;

public final class StockSelectAnalysis {
  private StockSelectAnalysis() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface StockSelectAnalysisRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string date = 1;
    boolean hasDate();
    String getDate();
    
    // required string time = 2;
    boolean hasTime();
    String getTime();
    
    // repeated string stockID = 3;
    java.util.List<String> getStockIDList();
    int getStockIDCount();
    String getStockID(int index);
  }
  public static final class StockSelectAnalysisRequest extends
      com.google.protobuf.GeneratedMessage
      implements StockSelectAnalysisRequestOrBuilder {
    // Use StockSelectAnalysisRequest.newBuilder() to construct.
    private StockSelectAnalysisRequest(Builder builder) {
      super(builder);
    }
    private StockSelectAnalysisRequest(boolean noInit) {}
    
    private static final StockSelectAnalysisRequest defaultInstance;
    public static StockSelectAnalysisRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public StockSelectAnalysisRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return stormstock.fw.event.StockSelectAnalysis.internal_static_stormstock_fw_event_StockSelectAnalysisRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return stormstock.fw.event.StockSelectAnalysis.internal_static_stormstock_fw_event_StockSelectAnalysisRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string date = 1;
    public static final int DATE_FIELD_NUMBER = 1;
    private java.lang.Object date_;
    public boolean hasDate() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          date_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string time = 2;
    public static final int TIME_FIELD_NUMBER = 2;
    private java.lang.Object time_;
    public boolean hasTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getTime() {
      java.lang.Object ref = time_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          time_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTimeBytes() {
      java.lang.Object ref = time_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated string stockID = 3;
    public static final int STOCKID_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList stockID_;
    public java.util.List<String>
        getStockIDList() {
      return stockID_;
    }
    public int getStockIDCount() {
      return stockID_.size();
    }
    public String getStockID(int index) {
      return stockID_.get(index);
    }
    
    private void initFields() {
      date_ = "";
      time_ = "";
      stockID_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDateBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTimeBytes());
      }
      for (int i = 0; i < stockID_.size(); i++) {
        output.writeBytes(3, stockID_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDateBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTimeBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < stockID_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(stockID_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getStockIDList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return stormstock.fw.event.StockSelectAnalysis.internal_static_stormstock_fw_event_StockSelectAnalysisRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return stormstock.fw.event.StockSelectAnalysis.internal_static_stormstock_fw_event_StockSelectAnalysisRequest_fieldAccessorTable;
      }
      
      // Construct using stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        date_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        stockID_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisRequest.getDescriptor();
      }
      
      public stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisRequest getDefaultInstanceForType() {
        return stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisRequest.getDefaultInstance();
      }
      
      public stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisRequest build() {
        stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisRequest buildPartial() {
        stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisRequest result = new stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.date_ = date_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.time_ = time_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          stockID_ = new com.google.protobuf.UnmodifiableLazyStringList(
              stockID_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.stockID_ = stockID_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisRequest) {
          return mergeFrom((stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisRequest other) {
        if (other == stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisRequest.getDefaultInstance()) return this;
        if (other.hasDate()) {
          setDate(other.getDate());
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (!other.stockID_.isEmpty()) {
          if (stockID_.isEmpty()) {
            stockID_ = other.stockID_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureStockIDIsMutable();
            stockID_.addAll(other.stockID_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasDate()) {
          
          return false;
        }
        if (!hasTime()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              date_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              time_ = input.readBytes();
              break;
            }
            case 26: {
              ensureStockIDIsMutable();
              stockID_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string date = 1;
      private java.lang.Object date_ = "";
      public boolean hasDate() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          date_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDate(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        date_ = value;
        onChanged();
        return this;
      }
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000001);
        date_ = getDefaultInstance().getDate();
        onChanged();
        return this;
      }
      void setDate(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        date_ = value;
        onChanged();
      }
      
      // required string time = 2;
      private java.lang.Object time_ = "";
      public boolean hasTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getTime() {
        java.lang.Object ref = time_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          time_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTime(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        time_ = value;
        onChanged();
        return this;
      }
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        time_ = getDefaultInstance().getTime();
        onChanged();
        return this;
      }
      void setTime(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        time_ = value;
        onChanged();
      }
      
      // repeated string stockID = 3;
      private com.google.protobuf.LazyStringList stockID_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureStockIDIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          stockID_ = new com.google.protobuf.LazyStringArrayList(stockID_);
          bitField0_ |= 0x00000004;
         }
      }
      public java.util.List<String>
          getStockIDList() {
        return java.util.Collections.unmodifiableList(stockID_);
      }
      public int getStockIDCount() {
        return stockID_.size();
      }
      public String getStockID(int index) {
        return stockID_.get(index);
      }
      public Builder setStockID(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStockIDIsMutable();
        stockID_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addStockID(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStockIDIsMutable();
        stockID_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllStockID(
          java.lang.Iterable<String> values) {
        ensureStockIDIsMutable();
        super.addAll(values, stockID_);
        onChanged();
        return this;
      }
      public Builder clearStockID() {
        stockID_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      void addStockID(com.google.protobuf.ByteString value) {
        ensureStockIDIsMutable();
        stockID_.add(value);
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:stormstock.fw.event.StockSelectAnalysisRequest)
    }
    
    static {
      defaultInstance = new StockSelectAnalysisRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:stormstock.fw.event.StockSelectAnalysisRequest)
  }
  
  public interface StockSelectAnalysisCompleteNotifyOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string date = 1;
    boolean hasDate();
    String getDate();
    
    // required string time = 2;
    boolean hasTime();
    String getTime();
    
    // repeated string StockID = 3;
    java.util.List<String> getStockIDList();
    int getStockIDCount();
    String getStockID(int index);
  }
  public static final class StockSelectAnalysisCompleteNotify extends
      com.google.protobuf.GeneratedMessage
      implements StockSelectAnalysisCompleteNotifyOrBuilder {
    // Use StockSelectAnalysisCompleteNotify.newBuilder() to construct.
    private StockSelectAnalysisCompleteNotify(Builder builder) {
      super(builder);
    }
    private StockSelectAnalysisCompleteNotify(boolean noInit) {}
    
    private static final StockSelectAnalysisCompleteNotify defaultInstance;
    public static StockSelectAnalysisCompleteNotify getDefaultInstance() {
      return defaultInstance;
    }
    
    public StockSelectAnalysisCompleteNotify getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return stormstock.fw.event.StockSelectAnalysis.internal_static_stormstock_fw_event_StockSelectAnalysisCompleteNotify_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return stormstock.fw.event.StockSelectAnalysis.internal_static_stormstock_fw_event_StockSelectAnalysisCompleteNotify_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string date = 1;
    public static final int DATE_FIELD_NUMBER = 1;
    private java.lang.Object date_;
    public boolean hasDate() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          date_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string time = 2;
    public static final int TIME_FIELD_NUMBER = 2;
    private java.lang.Object time_;
    public boolean hasTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getTime() {
      java.lang.Object ref = time_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          time_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTimeBytes() {
      java.lang.Object ref = time_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated string StockID = 3;
    public static final int STOCKID_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList stockID_;
    public java.util.List<String>
        getStockIDList() {
      return stockID_;
    }
    public int getStockIDCount() {
      return stockID_.size();
    }
    public String getStockID(int index) {
      return stockID_.get(index);
    }
    
    private void initFields() {
      date_ = "";
      time_ = "";
      stockID_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDateBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTimeBytes());
      }
      for (int i = 0; i < stockID_.size(); i++) {
        output.writeBytes(3, stockID_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDateBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTimeBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < stockID_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(stockID_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getStockIDList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisCompleteNotify parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisCompleteNotify parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisCompleteNotify parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisCompleteNotify parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisCompleteNotify parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisCompleteNotify parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisCompleteNotify parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisCompleteNotify parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisCompleteNotify parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisCompleteNotify parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisCompleteNotify prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisCompleteNotifyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return stormstock.fw.event.StockSelectAnalysis.internal_static_stormstock_fw_event_StockSelectAnalysisCompleteNotify_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return stormstock.fw.event.StockSelectAnalysis.internal_static_stormstock_fw_event_StockSelectAnalysisCompleteNotify_fieldAccessorTable;
      }
      
      // Construct using stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisCompleteNotify.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        date_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        stockID_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisCompleteNotify.getDescriptor();
      }
      
      public stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisCompleteNotify getDefaultInstanceForType() {
        return stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisCompleteNotify.getDefaultInstance();
      }
      
      public stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisCompleteNotify build() {
        stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisCompleteNotify result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisCompleteNotify buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisCompleteNotify result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisCompleteNotify buildPartial() {
        stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisCompleteNotify result = new stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisCompleteNotify(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.date_ = date_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.time_ = time_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          stockID_ = new com.google.protobuf.UnmodifiableLazyStringList(
              stockID_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.stockID_ = stockID_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisCompleteNotify) {
          return mergeFrom((stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisCompleteNotify)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisCompleteNotify other) {
        if (other == stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisCompleteNotify.getDefaultInstance()) return this;
        if (other.hasDate()) {
          setDate(other.getDate());
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (!other.stockID_.isEmpty()) {
          if (stockID_.isEmpty()) {
            stockID_ = other.stockID_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureStockIDIsMutable();
            stockID_.addAll(other.stockID_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasDate()) {
          
          return false;
        }
        if (!hasTime()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              date_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              time_ = input.readBytes();
              break;
            }
            case 26: {
              ensureStockIDIsMutable();
              stockID_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string date = 1;
      private java.lang.Object date_ = "";
      public boolean hasDate() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          date_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDate(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        date_ = value;
        onChanged();
        return this;
      }
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000001);
        date_ = getDefaultInstance().getDate();
        onChanged();
        return this;
      }
      void setDate(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        date_ = value;
        onChanged();
      }
      
      // required string time = 2;
      private java.lang.Object time_ = "";
      public boolean hasTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getTime() {
        java.lang.Object ref = time_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          time_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTime(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        time_ = value;
        onChanged();
        return this;
      }
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        time_ = getDefaultInstance().getTime();
        onChanged();
        return this;
      }
      void setTime(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        time_ = value;
        onChanged();
      }
      
      // repeated string StockID = 3;
      private com.google.protobuf.LazyStringList stockID_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureStockIDIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          stockID_ = new com.google.protobuf.LazyStringArrayList(stockID_);
          bitField0_ |= 0x00000004;
         }
      }
      public java.util.List<String>
          getStockIDList() {
        return java.util.Collections.unmodifiableList(stockID_);
      }
      public int getStockIDCount() {
        return stockID_.size();
      }
      public String getStockID(int index) {
        return stockID_.get(index);
      }
      public Builder setStockID(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStockIDIsMutable();
        stockID_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addStockID(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStockIDIsMutable();
        stockID_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllStockID(
          java.lang.Iterable<String> values) {
        ensureStockIDIsMutable();
        super.addAll(values, stockID_);
        onChanged();
        return this;
      }
      public Builder clearStockID() {
        stockID_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      void addStockID(com.google.protobuf.ByteString value) {
        ensureStockIDIsMutable();
        stockID_.add(value);
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:stormstock.fw.event.StockSelectAnalysisCompleteNotify)
    }
    
    static {
      defaultInstance = new StockSelectAnalysisCompleteNotify(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:stormstock.fw.event.StockSelectAnalysisCompleteNotify)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_stormstock_fw_event_StockSelectAnalysisRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_stormstock_fw_event_StockSelectAnalysisRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_stormstock_fw_event_StockSelectAnalysisCompleteNotify_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_stormstock_fw_event_StockSelectAnalysisCompleteNotify_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n1src/stormstock/fw/event/StockSelectAna" +
      "lysis.proto\022\023stormstock.fw.event\"I\n\032Stoc" +
      "kSelectAnalysisRequest\022\014\n\004date\030\001 \002(\t\022\014\n\004" +
      "time\030\002 \002(\t\022\017\n\007stockID\030\003 \003(\t\"P\n!StockSele" +
      "ctAnalysisCompleteNotify\022\014\n\004date\030\001 \002(\t\022\014" +
      "\n\004time\030\002 \002(\t\022\017\n\007StockID\030\003 \003(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_stormstock_fw_event_StockSelectAnalysisRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_stormstock_fw_event_StockSelectAnalysisRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_stormstock_fw_event_StockSelectAnalysisRequest_descriptor,
              new java.lang.String[] { "Date", "Time", "StockID", },
              stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisRequest.class,
              stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisRequest.Builder.class);
          internal_static_stormstock_fw_event_StockSelectAnalysisCompleteNotify_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_stormstock_fw_event_StockSelectAnalysisCompleteNotify_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_stormstock_fw_event_StockSelectAnalysisCompleteNotify_descriptor,
              new java.lang.String[] { "Date", "Time", "StockID", },
              stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisCompleteNotify.class,
              stormstock.fw.event.StockSelectAnalysis.StockSelectAnalysisCompleteNotify.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
