// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/stormstock/fw/event/StockCreateAnalysis.proto

package stormstock.fw.event;

public final class StockCreateAnalysis {
  private StockCreateAnalysis() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface StockCreateAnalysisRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string date = 1;
    boolean hasDate();
    String getDate();
    
    // required string time = 2;
    boolean hasTime();
    String getTime();
    
    // repeated string stockID = 3;
    java.util.List<String> getStockIDList();
    int getStockIDCount();
    String getStockID(int index);
  }
  public static final class StockCreateAnalysisRequest extends
      com.google.protobuf.GeneratedMessage
      implements StockCreateAnalysisRequestOrBuilder {
    // Use StockCreateAnalysisRequest.newBuilder() to construct.
    private StockCreateAnalysisRequest(Builder builder) {
      super(builder);
    }
    private StockCreateAnalysisRequest(boolean noInit) {}
    
    private static final StockCreateAnalysisRequest defaultInstance;
    public static StockCreateAnalysisRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public StockCreateAnalysisRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return stormstock.fw.event.StockCreateAnalysis.internal_static_stormstock_fw_event_StockCreateAnalysisRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return stormstock.fw.event.StockCreateAnalysis.internal_static_stormstock_fw_event_StockCreateAnalysisRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string date = 1;
    public static final int DATE_FIELD_NUMBER = 1;
    private java.lang.Object date_;
    public boolean hasDate() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          date_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string time = 2;
    public static final int TIME_FIELD_NUMBER = 2;
    private java.lang.Object time_;
    public boolean hasTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getTime() {
      java.lang.Object ref = time_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          time_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTimeBytes() {
      java.lang.Object ref = time_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated string stockID = 3;
    public static final int STOCKID_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList stockID_;
    public java.util.List<String>
        getStockIDList() {
      return stockID_;
    }
    public int getStockIDCount() {
      return stockID_.size();
    }
    public String getStockID(int index) {
      return stockID_.get(index);
    }
    
    private void initFields() {
      date_ = "";
      time_ = "";
      stockID_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDateBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTimeBytes());
      }
      for (int i = 0; i < stockID_.size(); i++) {
        output.writeBytes(3, stockID_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDateBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTimeBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < stockID_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(stockID_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getStockIDList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return stormstock.fw.event.StockCreateAnalysis.internal_static_stormstock_fw_event_StockCreateAnalysisRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return stormstock.fw.event.StockCreateAnalysis.internal_static_stormstock_fw_event_StockCreateAnalysisRequest_fieldAccessorTable;
      }
      
      // Construct using stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        date_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        stockID_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisRequest.getDescriptor();
      }
      
      public stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisRequest getDefaultInstanceForType() {
        return stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisRequest.getDefaultInstance();
      }
      
      public stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisRequest build() {
        stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisRequest buildPartial() {
        stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisRequest result = new stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.date_ = date_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.time_ = time_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          stockID_ = new com.google.protobuf.UnmodifiableLazyStringList(
              stockID_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.stockID_ = stockID_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisRequest) {
          return mergeFrom((stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisRequest other) {
        if (other == stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisRequest.getDefaultInstance()) return this;
        if (other.hasDate()) {
          setDate(other.getDate());
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (!other.stockID_.isEmpty()) {
          if (stockID_.isEmpty()) {
            stockID_ = other.stockID_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureStockIDIsMutable();
            stockID_.addAll(other.stockID_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasDate()) {
          
          return false;
        }
        if (!hasTime()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              date_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              time_ = input.readBytes();
              break;
            }
            case 26: {
              ensureStockIDIsMutable();
              stockID_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string date = 1;
      private java.lang.Object date_ = "";
      public boolean hasDate() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          date_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDate(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        date_ = value;
        onChanged();
        return this;
      }
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000001);
        date_ = getDefaultInstance().getDate();
        onChanged();
        return this;
      }
      void setDate(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        date_ = value;
        onChanged();
      }
      
      // required string time = 2;
      private java.lang.Object time_ = "";
      public boolean hasTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getTime() {
        java.lang.Object ref = time_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          time_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTime(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        time_ = value;
        onChanged();
        return this;
      }
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        time_ = getDefaultInstance().getTime();
        onChanged();
        return this;
      }
      void setTime(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        time_ = value;
        onChanged();
      }
      
      // repeated string stockID = 3;
      private com.google.protobuf.LazyStringList stockID_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureStockIDIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          stockID_ = new com.google.protobuf.LazyStringArrayList(stockID_);
          bitField0_ |= 0x00000004;
         }
      }
      public java.util.List<String>
          getStockIDList() {
        return java.util.Collections.unmodifiableList(stockID_);
      }
      public int getStockIDCount() {
        return stockID_.size();
      }
      public String getStockID(int index) {
        return stockID_.get(index);
      }
      public Builder setStockID(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStockIDIsMutable();
        stockID_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addStockID(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStockIDIsMutable();
        stockID_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllStockID(
          java.lang.Iterable<String> values) {
        ensureStockIDIsMutable();
        super.addAll(values, stockID_);
        onChanged();
        return this;
      }
      public Builder clearStockID() {
        stockID_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      void addStockID(com.google.protobuf.ByteString value) {
        ensureStockIDIsMutable();
        stockID_.add(value);
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:stormstock.fw.event.StockCreateAnalysisRequest)
    }
    
    static {
      defaultInstance = new StockCreateAnalysisRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:stormstock.fw.event.StockCreateAnalysisRequest)
  }
  
  public interface StockCreateAnalysisCompleteNotifyOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string date = 1;
    boolean hasDate();
    String getDate();
    
    // required string time = 2;
    boolean hasTime();
    String getTime();
    
    // repeated .stormstock.fw.event.StockCreateAnalysisCompleteNotify.CreateItem item = 3;
    java.util.List<stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem> 
        getItemList();
    stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem getItem(int index);
    int getItemCount();
    java.util.List<? extends stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItemOrBuilder> 
        getItemOrBuilderList();
    stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItemOrBuilder getItemOrBuilder(
        int index);
  }
  public static final class StockCreateAnalysisCompleteNotify extends
      com.google.protobuf.GeneratedMessage
      implements StockCreateAnalysisCompleteNotifyOrBuilder {
    // Use StockCreateAnalysisCompleteNotify.newBuilder() to construct.
    private StockCreateAnalysisCompleteNotify(Builder builder) {
      super(builder);
    }
    private StockCreateAnalysisCompleteNotify(boolean noInit) {}
    
    private static final StockCreateAnalysisCompleteNotify defaultInstance;
    public static StockCreateAnalysisCompleteNotify getDefaultInstance() {
      return defaultInstance;
    }
    
    public StockCreateAnalysisCompleteNotify getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return stormstock.fw.event.StockCreateAnalysis.internal_static_stormstock_fw_event_StockCreateAnalysisCompleteNotify_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return stormstock.fw.event.StockCreateAnalysis.internal_static_stormstock_fw_event_StockCreateAnalysisCompleteNotify_fieldAccessorTable;
    }
    
    public interface CreateItemOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // required string stockID = 1;
      boolean hasStockID();
      String getStockID();
      
      // required float price = 2;
      boolean hasPrice();
      float getPrice();
      
      // required int32 amount = 3;
      boolean hasAmount();
      int getAmount();
    }
    public static final class CreateItem extends
        com.google.protobuf.GeneratedMessage
        implements CreateItemOrBuilder {
      // Use CreateItem.newBuilder() to construct.
      private CreateItem(Builder builder) {
        super(builder);
      }
      private CreateItem(boolean noInit) {}
      
      private static final CreateItem defaultInstance;
      public static CreateItem getDefaultInstance() {
        return defaultInstance;
      }
      
      public CreateItem getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return stormstock.fw.event.StockCreateAnalysis.internal_static_stormstock_fw_event_StockCreateAnalysisCompleteNotify_CreateItem_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return stormstock.fw.event.StockCreateAnalysis.internal_static_stormstock_fw_event_StockCreateAnalysisCompleteNotify_CreateItem_fieldAccessorTable;
      }
      
      private int bitField0_;
      // required string stockID = 1;
      public static final int STOCKID_FIELD_NUMBER = 1;
      private java.lang.Object stockID_;
      public boolean hasStockID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getStockID() {
        java.lang.Object ref = stockID_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            stockID_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getStockIDBytes() {
        java.lang.Object ref = stockID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          stockID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      // required float price = 2;
      public static final int PRICE_FIELD_NUMBER = 2;
      private float price_;
      public boolean hasPrice() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public float getPrice() {
        return price_;
      }
      
      // required int32 amount = 3;
      public static final int AMOUNT_FIELD_NUMBER = 3;
      private int amount_;
      public boolean hasAmount() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getAmount() {
        return amount_;
      }
      
      private void initFields() {
        stockID_ = "";
        price_ = 0F;
        amount_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasStockID()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasPrice()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasAmount()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getStockIDBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeFloat(2, price_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeInt32(3, amount_);
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getStockIDBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(2, price_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, amount_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItemOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return stormstock.fw.event.StockCreateAnalysis.internal_static_stormstock_fw_event_StockCreateAnalysisCompleteNotify_CreateItem_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return stormstock.fw.event.StockCreateAnalysis.internal_static_stormstock_fw_event_StockCreateAnalysisCompleteNotify_CreateItem_fieldAccessorTable;
        }
        
        // Construct using stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          stockID_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          price_ = 0F;
          bitField0_ = (bitField0_ & ~0x00000002);
          amount_ = 0;
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem.getDescriptor();
        }
        
        public stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem getDefaultInstanceForType() {
          return stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem.getDefaultInstance();
        }
        
        public stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem build() {
          stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem buildPartial() {
          stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem result = new stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.stockID_ = stockID_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.price_ = price_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.amount_ = amount_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem) {
            return mergeFrom((stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem other) {
          if (other == stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem.getDefaultInstance()) return this;
          if (other.hasStockID()) {
            setStockID(other.getStockID());
          }
          if (other.hasPrice()) {
            setPrice(other.getPrice());
          }
          if (other.hasAmount()) {
            setAmount(other.getAmount());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasStockID()) {
            
            return false;
          }
          if (!hasPrice()) {
            
            return false;
          }
          if (!hasAmount()) {
            
            return false;
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                stockID_ = input.readBytes();
                break;
              }
              case 21: {
                bitField0_ |= 0x00000002;
                price_ = input.readFloat();
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                amount_ = input.readInt32();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // required string stockID = 1;
        private java.lang.Object stockID_ = "";
        public boolean hasStockID() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public String getStockID() {
          java.lang.Object ref = stockID_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            stockID_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setStockID(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          stockID_ = value;
          onChanged();
          return this;
        }
        public Builder clearStockID() {
          bitField0_ = (bitField0_ & ~0x00000001);
          stockID_ = getDefaultInstance().getStockID();
          onChanged();
          return this;
        }
        void setStockID(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000001;
          stockID_ = value;
          onChanged();
        }
        
        // required float price = 2;
        private float price_ ;
        public boolean hasPrice() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public float getPrice() {
          return price_;
        }
        public Builder setPrice(float value) {
          bitField0_ |= 0x00000002;
          price_ = value;
          onChanged();
          return this;
        }
        public Builder clearPrice() {
          bitField0_ = (bitField0_ & ~0x00000002);
          price_ = 0F;
          onChanged();
          return this;
        }
        
        // required int32 amount = 3;
        private int amount_ ;
        public boolean hasAmount() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        public int getAmount() {
          return amount_;
        }
        public Builder setAmount(int value) {
          bitField0_ |= 0x00000004;
          amount_ = value;
          onChanged();
          return this;
        }
        public Builder clearAmount() {
          bitField0_ = (bitField0_ & ~0x00000004);
          amount_ = 0;
          onChanged();
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:stormstock.fw.event.StockCreateAnalysisCompleteNotify.CreateItem)
      }
      
      static {
        defaultInstance = new CreateItem(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:stormstock.fw.event.StockCreateAnalysisCompleteNotify.CreateItem)
    }
    
    private int bitField0_;
    // required string date = 1;
    public static final int DATE_FIELD_NUMBER = 1;
    private java.lang.Object date_;
    public boolean hasDate() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getDate() {
      java.lang.Object ref = date_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          date_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string time = 2;
    public static final int TIME_FIELD_NUMBER = 2;
    private java.lang.Object time_;
    public boolean hasTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getTime() {
      java.lang.Object ref = time_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          time_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTimeBytes() {
      java.lang.Object ref = time_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .stormstock.fw.event.StockCreateAnalysisCompleteNotify.CreateItem item = 3;
    public static final int ITEM_FIELD_NUMBER = 3;
    private java.util.List<stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem> item_;
    public java.util.List<stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem> getItemList() {
      return item_;
    }
    public java.util.List<? extends stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItemOrBuilder> 
        getItemOrBuilderList() {
      return item_;
    }
    public int getItemCount() {
      return item_.size();
    }
    public stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem getItem(int index) {
      return item_.get(index);
    }
    public stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItemOrBuilder getItemOrBuilder(
        int index) {
      return item_.get(index);
    }
    
    private void initFields() {
      date_ = "";
      time_ = "";
      item_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getItemCount(); i++) {
        if (!getItem(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDateBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTimeBytes());
      }
      for (int i = 0; i < item_.size(); i++) {
        output.writeMessage(3, item_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDateBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTimeBytes());
      }
      for (int i = 0; i < item_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, item_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotifyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return stormstock.fw.event.StockCreateAnalysis.internal_static_stormstock_fw_event_StockCreateAnalysisCompleteNotify_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return stormstock.fw.event.StockCreateAnalysis.internal_static_stormstock_fw_event_StockCreateAnalysisCompleteNotify_fieldAccessorTable;
      }
      
      // Construct using stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getItemFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        date_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (itemBuilder_ == null) {
          item_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          itemBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.getDescriptor();
      }
      
      public stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify getDefaultInstanceForType() {
        return stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.getDefaultInstance();
      }
      
      public stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify build() {
        stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify buildPartial() {
        stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify result = new stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.date_ = date_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.time_ = time_;
        if (itemBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            item_ = java.util.Collections.unmodifiableList(item_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.item_ = item_;
        } else {
          result.item_ = itemBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify) {
          return mergeFrom((stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify other) {
        if (other == stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.getDefaultInstance()) return this;
        if (other.hasDate()) {
          setDate(other.getDate());
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (itemBuilder_ == null) {
          if (!other.item_.isEmpty()) {
            if (item_.isEmpty()) {
              item_ = other.item_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureItemIsMutable();
              item_.addAll(other.item_);
            }
            onChanged();
          }
        } else {
          if (!other.item_.isEmpty()) {
            if (itemBuilder_.isEmpty()) {
              itemBuilder_.dispose();
              itemBuilder_ = null;
              item_ = other.item_;
              bitField0_ = (bitField0_ & ~0x00000004);
              itemBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getItemFieldBuilder() : null;
            } else {
              itemBuilder_.addAllMessages(other.item_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasDate()) {
          
          return false;
        }
        if (!hasTime()) {
          
          return false;
        }
        for (int i = 0; i < getItemCount(); i++) {
          if (!getItem(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              date_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              time_ = input.readBytes();
              break;
            }
            case 26: {
              stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem.Builder subBuilder = stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addItem(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string date = 1;
      private java.lang.Object date_ = "";
      public boolean hasDate() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getDate() {
        java.lang.Object ref = date_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          date_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDate(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        date_ = value;
        onChanged();
        return this;
      }
      public Builder clearDate() {
        bitField0_ = (bitField0_ & ~0x00000001);
        date_ = getDefaultInstance().getDate();
        onChanged();
        return this;
      }
      void setDate(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        date_ = value;
        onChanged();
      }
      
      // required string time = 2;
      private java.lang.Object time_ = "";
      public boolean hasTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getTime() {
        java.lang.Object ref = time_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          time_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTime(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        time_ = value;
        onChanged();
        return this;
      }
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        time_ = getDefaultInstance().getTime();
        onChanged();
        return this;
      }
      void setTime(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        time_ = value;
        onChanged();
      }
      
      // repeated .stormstock.fw.event.StockCreateAnalysisCompleteNotify.CreateItem item = 3;
      private java.util.List<stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem> item_ =
        java.util.Collections.emptyList();
      private void ensureItemIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          item_ = new java.util.ArrayList<stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem>(item_);
          bitField0_ |= 0x00000004;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem, stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem.Builder, stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItemOrBuilder> itemBuilder_;
      
      public java.util.List<stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem> getItemList() {
        if (itemBuilder_ == null) {
          return java.util.Collections.unmodifiableList(item_);
        } else {
          return itemBuilder_.getMessageList();
        }
      }
      public int getItemCount() {
        if (itemBuilder_ == null) {
          return item_.size();
        } else {
          return itemBuilder_.getCount();
        }
      }
      public stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem getItem(int index) {
        if (itemBuilder_ == null) {
          return item_.get(index);
        } else {
          return itemBuilder_.getMessage(index);
        }
      }
      public Builder setItem(
          int index, stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem value) {
        if (itemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemIsMutable();
          item_.set(index, value);
          onChanged();
        } else {
          itemBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setItem(
          int index, stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem.Builder builderForValue) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addItem(stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem value) {
        if (itemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemIsMutable();
          item_.add(value);
          onChanged();
        } else {
          itemBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addItem(
          int index, stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem value) {
        if (itemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemIsMutable();
          item_.add(index, value);
          onChanged();
        } else {
          itemBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addItem(
          stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem.Builder builderForValue) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.add(builderForValue.build());
          onChanged();
        } else {
          itemBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addItem(
          int index, stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem.Builder builderForValue) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllItem(
          java.lang.Iterable<? extends stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem> values) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          super.addAll(values, item_);
          onChanged();
        } else {
          itemBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearItem() {
        if (itemBuilder_ == null) {
          item_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          itemBuilder_.clear();
        }
        return this;
      }
      public Builder removeItem(int index) {
        if (itemBuilder_ == null) {
          ensureItemIsMutable();
          item_.remove(index);
          onChanged();
        } else {
          itemBuilder_.remove(index);
        }
        return this;
      }
      public stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem.Builder getItemBuilder(
          int index) {
        return getItemFieldBuilder().getBuilder(index);
      }
      public stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItemOrBuilder getItemOrBuilder(
          int index) {
        if (itemBuilder_ == null) {
          return item_.get(index);  } else {
          return itemBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItemOrBuilder> 
           getItemOrBuilderList() {
        if (itemBuilder_ != null) {
          return itemBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(item_);
        }
      }
      public stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem.Builder addItemBuilder() {
        return getItemFieldBuilder().addBuilder(
            stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem.getDefaultInstance());
      }
      public stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem.Builder addItemBuilder(
          int index) {
        return getItemFieldBuilder().addBuilder(
            index, stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem.getDefaultInstance());
      }
      public java.util.List<stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem.Builder> 
           getItemBuilderList() {
        return getItemFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem, stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem.Builder, stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItemOrBuilder> 
          getItemFieldBuilder() {
        if (itemBuilder_ == null) {
          itemBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem, stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem.Builder, stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItemOrBuilder>(
                  item_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          item_ = null;
        }
        return itemBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:stormstock.fw.event.StockCreateAnalysisCompleteNotify)
    }
    
    static {
      defaultInstance = new StockCreateAnalysisCompleteNotify(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:stormstock.fw.event.StockCreateAnalysisCompleteNotify)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_stormstock_fw_event_StockCreateAnalysisRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_stormstock_fw_event_StockCreateAnalysisRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_stormstock_fw_event_StockCreateAnalysisCompleteNotify_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_stormstock_fw_event_StockCreateAnalysisCompleteNotify_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_stormstock_fw_event_StockCreateAnalysisCompleteNotify_CreateItem_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_stormstock_fw_event_StockCreateAnalysisCompleteNotify_CreateItem_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n1src/stormstock/fw/event/StockCreateAna" +
      "lysis.proto\022\023stormstock.fw.event\"I\n\032Stoc" +
      "kCreateAnalysisRequest\022\014\n\004date\030\001 \002(\t\022\014\n\004" +
      "time\030\002 \002(\t\022\017\n\007stockID\030\003 \003(\t\"\316\001\n!StockCre" +
      "ateAnalysisCompleteNotify\022\014\n\004date\030\001 \002(\t\022" +
      "\014\n\004time\030\002 \002(\t\022O\n\004item\030\003 \003(\0132A.stormstock" +
      ".fw.event.StockCreateAnalysisCompleteNot" +
      "ify.CreateItem\032<\n\nCreateItem\022\017\n\007stockID\030" +
      "\001 \002(\t\022\r\n\005price\030\002 \002(\002\022\016\n\006amount\030\003 \002(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_stormstock_fw_event_StockCreateAnalysisRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_stormstock_fw_event_StockCreateAnalysisRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_stormstock_fw_event_StockCreateAnalysisRequest_descriptor,
              new java.lang.String[] { "Date", "Time", "StockID", },
              stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisRequest.class,
              stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisRequest.Builder.class);
          internal_static_stormstock_fw_event_StockCreateAnalysisCompleteNotify_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_stormstock_fw_event_StockCreateAnalysisCompleteNotify_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_stormstock_fw_event_StockCreateAnalysisCompleteNotify_descriptor,
              new java.lang.String[] { "Date", "Time", "Item", },
              stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.class,
              stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.Builder.class);
          internal_static_stormstock_fw_event_StockCreateAnalysisCompleteNotify_CreateItem_descriptor =
            internal_static_stormstock_fw_event_StockCreateAnalysisCompleteNotify_descriptor.getNestedTypes().get(0);
          internal_static_stormstock_fw_event_StockCreateAnalysisCompleteNotify_CreateItem_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_stormstock_fw_event_StockCreateAnalysisCompleteNotify_CreateItem_descriptor,
              new java.lang.String[] { "StockID", "Price", "Amount", },
              stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem.class,
              stormstock.fw.event.StockCreateAnalysis.StockCreateAnalysisCompleteNotify.CreateItem.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
