/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class stormstock_ori_capi_CATHSAccount_ResultTotalAssets */

#ifndef _Included_stormstock_ori_capi_CATHSAccount_ResultTotalAssets
#define _Included_stormstock_ori_capi_CATHSAccount_ResultTotalAssets
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
