/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class stormstock_ori_capi_CATHSAccount_CommissionOrder */

#ifndef _Included_stormstock_ori_capi_CATHSAccount_CommissionOrder
#define _Included_stormstock_ori_capi_CATHSAccount_CommissionOrder
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
